/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import enMessage from '../locales/en/messages.json';
import koMessage from '../locales/ko/messages.json';

export function getMessageFromLocale(locale: string) {
  switch (locale) {
    case 'en':
      return enMessage;
    case 'ko':
      return koMessage;
    default:
      throw new Error('Unsupported locale');
  }
}

export const defaultLocale = Intl.DateTimeFormat().resolvedOptions().locale.split('_')[0];
