/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type koMessage from '../locales/ko/messages.json';

type EnsureSameKeys<T, U> = keyof T extends keyof U ? (keyof U extends keyof T ? true : never) : never;

type KeyCheck = EnsureSameKeys<typeof enMessage, typeof koMessage>;

export type MessageKey = KeyCheck extends true ? keyof typeof enMessage : never;

export type DevLocale = 'en' | 'ko';
