/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type koMessage from '../locales/ko/messages.json';

export type MessageKey = keyof typeof enMessage & keyof typeof koMessage;

export type DevLocale = 'en' | 'ko';
