version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    insecure-external-code-execution: deny
    labels:
      - "dependencies"
      - "npm"
    groups:
      dev-dependencies:
        patterns:
          - "*"
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
