packages:
  - chrome-extension
  - pages/*
  - packages/*
  - tests/*
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver
