name: Make sure new PRs are sent to development

on:
  pull_request_target:
    types: [ opened, edited, reopened, synchronize ]
  push:
    types: [ created, edited, reopened, synchronize ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: Vankka/pr-target-branch-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: dev
          change-to: dev
          comment: |
            Your PR's base branch was set to `main`, PRs should be set to target `development`.
            The base branch of this PR has been automatically changed to `dev`, please check that there are no merge conflicts
            TEST
          already-exists-action: close_other_continue
          already-exists-comment: "Closing {url} as it has the same base branch"
          already-exists-other-comment: "This PR was closed in favor of {url}"